version: '3.8'

services:
  backend:
    build:
      context: ./clicker-backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/musicAnnotationApp
    depends_on:
      - mongo

  frontend:
    build:
      context: ./clicker-frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: